version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=jumpserver
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    volumes:
      - "mysql_data_volume:/var/lib/mysql"
      - "./mysql/initdb.d:/docker-entrypoint-initdb.d"
    networks:
      jumpserver-network:
        aliases:
          - jumpserver-mysql
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
#    deploy:
#      placement:
#        constraints:
#          - node.labels.role==mysql

  redis:
    image: redis:alpine
    volumes:
      - type: volume
        source: redis_data_volume
        target: /data
    networks:
      jumpserver-network:
        aliases:
          - jumpserver-redis
    entrypoint:
      - redis-server
   #   - /usr/local/etc/redis/redis.conf
      - --appendonly
      - "yes"
#    deploy:
#      placement:
#        constraints:
#          - node.labels.role==redis


  jumpserver-app:
    build:
      context: ./jumpserver-app
    image: azleal/jumpserver-app
    environment:
      BOOTSTRAP_TOKEN_FILE: /run/secrets/bootstrap_token
      SECRET_KEY_FILE: /run/secrets/secret_key
#      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - jumpserver_logs_volume:/opt/jumpserver/logs
      - jumpserver_data_volume:/opt/jumpserver/data
    secrets:
      - bootstrap_token
      - secret_key
      - mysql_user
      - mysql_password
    networks:
      jumpserver-network:
    depends_on:
      - redis
      - mysql

  coco:
    build:
      context: jumpserver-coco
    image: azleal/jumpserver-coco:1.4.10
    networks:
      jumpserver-network:
    environment:
      BOOTSTRAP_TOKEN_FILE: /run/secrets/bootstrap_token
    secrets:
      - bootstrap_token
    depends_on:
      - jumpserver-app

  # 8081
  guacamole:
    build:
      context: ./jumpserver-guacamole
    image: azleal/jumpserver-guacamole:1.5.0
    networks:
      jumpserver-network:
    environment:
      - BOOTSTRAP_TOKEN=2GXCRnuIDOdStqblJA1k
    depends_on:
      - jumpserver-app

  openresty:
    build:
      context: ./openresty
    image: azleal/openresty
    networks:
      jumpserver-network:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - jumpserver_data_volume:/opt/jumpserver/data:ro
    depends_on:
      - jumpserver-app


configs:
  redis.conf:
    file: ./redis/conf/redis.conf

secrets:
  bootstrap_token:
    file: ./secrets/bootstrap_token
  secret_key:
    file: ./secrets/secret_key
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user:
    file: ./secrets/mysql_user
  mysql_password:
    file: ./secrets/mysql_password


volumes:
  mysql_data_volume:
  redis_data_volume:
  jumpserver_logs_volume:
  jumpserver_data_volume:

networks:
  jumpserver-network:
    driver: overlay
